### PR TITLE
Fix current_resource_record_set and add alias_target data

### PR DESCRIPTION
**Pull request by palexvs**
- Find record with current type. It fixes issue that happens when you have a few records for the same name (ex.: A, MX, ...)
- Add `alias_target` data

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @palexvs

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
Thanks @palexvs. I'm curious if you have any feedback on the cookbook since you're one of the first users to experience the rewrite?

**Comment by palexvs** [comment]
@tas50 , It works much faster now and I don't have exception 'Throttling => Rate exceeded' anymore. I like it.

**Pull request merged**
