### PR TITLE
Bump fog version

### LINKED ISSUE #69: fog-aws 0.1.2 breaks this cookbook
Not sure if this is something that you guys want to investigate, but the 0.1.2 release of fog-aws seems to break this cookbook.

https://github.com/fog/fog-aws/issues/83

The solution in that issue is to replace fog with fog-aws. I know that PR #67 is about moving from fog to fog-aws, but there were concerns about breaking other functionality.

### PR DESCRIPTION
**Pull request by plribeiro3000**
fixes #69

### CODE REVIEW

**Comment by plribeiro3000** [comment]
I just realized i have merge permissions here. 

Can i go ahead and merge this?

cc/ @chrisroberts @slyness @agoddard

**Comment by slyness** [comment]
This is an attribute which you can override with a role or your own recipe. Not really any need to rush a merge on something like this. I will be looking at going through open issues and PRs this Friday.

**Comment by josacar** [comment]
if this is a requirement of `fog-aws, why is not enforcing minimum required `fog` or `fog-core`?

**Comment by plribeiro3000** [comment]
`fog` is a meta gem for all providers. `fog-aws` depends on `fog-core` which does not depend on `fog` at all.
There is a relation from `fog` to `fog-aws` but there is none from `fog-aws` to `fog`.

Force core versions isn't really a good idea since we have a lot of providers that aren't much of active. If each provider force a specific version of `fog-core`, `fog` will just break.

This scenario give us 2 possible solutions:
* Depend only of `fog-aws` (which we already have an open PR #67)
* Bump `fog` version from time to time. (this PR)

**Comment by josacar** [comment]
As long as it's an `AWS`-specific feature I think we should depend on `fog-aws` or if we want to get rid of it, migrate to `aws-sdk`

**Comment by palexvs** [comment]
@slyness  , I get error when I try to override fog version in role:
```
[2015-11-16T08:44:44-08:00] INFO: package[libxslt-dev] is a virtual package, actually acting on package[libxslt1-dev]

================================================================================
Error executing action `install` on resource 'chef_gem[fog]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" ----
STDOUT: 
STDERR: ERROR:  Error installing fog:
	fog-google requires Ruby version >= 2.0.
---- End output of /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" ----
Ran /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" returned 1

Resource Declaration:
---------------------
# In /tmp/chef-solo/site-cookbooks/route53/recipes/default.rb

 22: chef_gem "fog" do
 23:   action :install
 24:   version node['route53']['fog_version']
 25: end
 26: 

Compiled Resource:
------------------
# Declared in /tmp/chef-solo/site-cookbooks/route53/recipes/default.rb:22:in `from_file'

chef_gem("fog") do
  provider Chef::Provider::Package::Rubygems
  action [:install]
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "fog"
  version "1.30"
  timeout 900
  gem_binary "/opt/chef/embedded/bin/gem"
  cookbook_name :route53
  recipe_name "default"
end


================================================================================
Recipe Compile Error in /tmp/chef-solo/site-cookbooks/route53/recipes/default.rb
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
chef_gem[fog] (route53::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" ----
STDOUT: 
STDERR: ERROR:  Error installing fog:
	fog-google requires Ruby version >= 2.0.
---- End output of /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" ----
Ran /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" returned 1

Cookbook Trace:
---------------
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:272:in `invalid!'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:259:in `error!'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:43:in `shell_out!'
  /opt/chef/embedded/apps/chef/lib/chef/provider/package/rubygems.rb:538:in `install_via_gem_command'
  /opt/chef/embedded/apps/chef/lib/chef/provider/package/rubygems.rb:522:in `install_package'
  /opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:82:in `block in action_install'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:156:in `converge_by'
  /opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:80:in `action_install'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:121:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/resource.rb:648:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/resource/chef_gem.rb:48:in `block in after_created'
  /opt/chef/embedded/apps/chef/lib/chef/resource/chef_gem.rb:47:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/resource/chef_gem.rb:47:in `after_created'
  /opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:139:in `build_resource'
  /opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:85:in `declare_resource'
  /opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:41:in `method_missing'
  /tmp/chef-solo/site-cookbooks/route53/recipes/default.rb:22:in `from_file'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
  /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:234:in `load_recipe'
  /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:166:in `load_recipe'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
  /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:89:in `load'
  /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:265:in `setup_run_context'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:429:in `do_run'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:213:in `block in run'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:236:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:226:in `block in run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:218:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:218:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:55:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
  /usr/bin/chef-solo:38:in `load'
  /usr/bin/chef-solo:38:in `<main>'

Relevant File Content:
----------------------
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.6.1/lib/mixlib/shellout.rb:

265:      # +msg+:  A String to use as the basis of the exception message. The
266:      # default explanation is very generic, providing a more informative message
267:      # is highly encouraged.
268:      # === Raises
269:      # ShellCommandFailed  always
270:      def invalid!(msg=nil)
271:        msg ||= "Command produced unexpected results"
272>>       raise ShellCommandFailed, msg + "\n" + format_for_exception
273:      end
274:  
275:      def inspect
276:        "<#{self.class.name}##{object_id}: command: '#@command' process_status: #{@status.inspect} " +
277:        "stdout: '#{stdout.strip}' stderr: '#{stderr.strip}' child_pid: #{@child_pid.inspect} " +
278:        "environment: #{@environment.inspect} timeout: #{timeout} user: #@user group: #@group working_dir: #@cwd >"
279:      end
280:  
281:      private

[2015-11-16T08:44:48-08:00] ERROR: Running exception handlers
[2015-11-16T08:44:48-08:00] ERROR: Exception handlers complete
[2015-11-16T08:44:48-08:00] FATAL: Stacktrace dumped to /tmp/chef-solo/cache/chef-stacktrace.out
[2015-11-16T08:44:48-08:00] ERROR: chef_gem[fog] (route53::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" ----
STDOUT: 
STDERR: ERROR:  Error installing fog:
	fog-google requires Ruby version >= 2.0.
---- End output of /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" ----
Ran /opt/chef/embedded/bin/gem install fog -q --no-rdoc --no-ri -v "1.30" returned 1
[2015-11-16T08:44:48-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

FAILED: chef-solo could not finish configuring the node
```


As i understand the issue is in ruby version, but how it can be changed?

**Comment by plribeiro3000** [comment]
The issue lies here:
`fog-google requires Ruby version >= 2.0.`
and here:
`/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/`

So it seems you are not using version `2.2.2` after all.

**Comment by palexvs** [comment]
@plribeiro3000 , seem like 

I use ubuntu 14.04 and when I after installing chef (`fix -d -y node:host_name deploy_chef:version=11.18.12`) it uses 1.9.1 ruby, and did not find how to change it :(

**Comment by slyness** [comment]
At this point 1.30 is not current. I'll go ahead and bump to '1.37.0' in #85 and close this PR. Thank you for contributing.

**Comment by plribeiro3000** [comment]
Awesome. Thank you!

Em sex, 4 de mar de 2016 10:05, Aaron Baer <notifications@github.com>
escreveu:

**Pull request closed without merging**
